name: Apply Sonar Fix

on:
  workflow_dispatch:

jobs:
  sonar-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug repo
        run: |
          pwd
          ls -la

      - name: Run sonar fix
        run: python3 scripts/sonar_fix.py

      - name: Create Pull Request if changes
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: add sonar java libraries and test binaries"
          title: "Add sonar java libraries and test binaries"
          body: "Automated update of sonar-project.properties"
          branch: chore/sonar-libraries-fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
